language: php

php:
  - 7.1.3

services:
  - docker

before_install:
  - php -v
  - which php
  - sudo cp -rf software/codecept.phar /usr/local/bin/codecept
  - sudo chmod a+x /usr/local/bin/codecept
  - which codecept
  - codecept -v

install:
  - docker build -t sunnyyii2 .
  - docker run -d --name=sunnyyii2 -p 8087:8092 -v extini:/usr/local/php/etc/php.d -v extfile:/data/phpext -v php_demo:/data/www sunnyyii2

script:
  - docker ps | grep -q sunnyyii2
  - make test
